services:
    redis:
        image: redis:latest
        container_name: twitter-clone-redis
        restart: always
        ports:
            - ${REDISPORT}:${REDISPORT}
        networks:
            - tc-network
networks:
    tc-network:
        external: true
        driver: bridge